# Generated by fusen: do not edit by hand

library(testthat)
test_that("The bmi function calculates the BMI correctly with the given example", {
  test_bmi <- bmi(mass = 80, height = 1.80)
  expect_equal(test_bmi, 24.7)
})
