# Generated by fusen: do not edit by hand

library(testthat)
datafile <- system.file("toydatasets.xlsx", package = "berraerkosar")
the_list <- multi_import_excel(datafile)
test_that("multi_import_excel works properly and show error if needed", {
  expect_true(length(the_list) ==3)
})
