# Generated by fusen: do not edit by hand

#' BMI
#'
#' @param mass Enter the weight in kg
#' @param height Enter the height in meters
#' @return Returns the body mass index (BMI)
#' 
#' @export
#'
#' @examples
#' library(dplyr)
#' 
#' bmi(mass = 80, height = 1.80) # Should give 24.7
#' 
#' #To insert BMI column on a data frame
#' data("data_weight")
#' data_weight %>%
#'   mutate(bmi = bmi(mass = mass, height = height))
bmi <- function(mass, height){
  mass <- as.numeric(mass)
  height <- as.numeric(height)
  bmi_calculated <- mass/(height * height)
  return(round(bmi_calculated, digits = 1))
}
