# Generated by fusen: do not edit by hand

library(purrr)
library(readxl)

#' multi_import_excel
#'
#' @param filename The excel file
#'
#' @return list of sheets
#' @export
#'
#' @examples
#' datafile <- system.file("toydatasets.xlsx", package = "berraerkosar")
#' multi_import_excel(datafile)
multi_import_excel <- function(filename) {
my_sheets <- readxl::excel_sheets(datafile)
return(my_sheets)
}


